version: '3.8'
services:
  hapi-fhir:
    image: "hapiproject/hapi:latest"
    depends_on:
      - hapi-db
    volumes:
      - ./hapi-config:/data/hapi
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://hapi-db:5433/root'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'hapifhir2023'
      SPRING_DATASOURCE_DRIVERCLASSNAME: 'org.postgresql.Driver'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect'

  hapi-db:
    image: "postgres:14.6"
    restart: always
    user: root
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "hapifhir2023"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 10s
      retries: 5
    command: -p 5433
    
  hapi-fhir-bundle-signer:
    build:
      context: ./bundle-signer
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PROD_HAPI_FHIR: "http://hapi-fhir:8080"
      DDCC_URL: "http://ddcc:4321/ddcc"
      EXTERNAL_HAPI_FHIR: "http://lacpass.create.cl:8080/fhir"
      PROD_PRIVATE_KEY_FILE: "./static/key.pem"
    volumes:
      - ./bundle-signer/static:/usr/src/app/static


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    volumes:
      - ./elastic:/var/lib/elasticsearch/data
    networks:
      elastic:
        aliases:
          - es
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://es:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 2g


  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g -jar snowstorm.jar --elasticsearch.urls=http://es:9200 --delete-indices --import=/snomed/SnomedCT_IPSTerminologyRelease.zip
    networks:
      elastic:
        aliases:
          - snowstorm
    volumes:
      - ./snomed:/snomed
    ports:
      - 8000:8080

  snowstorm-browser:
    image: snomedinternational/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
    networks:
      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 8082:80
    restart: always

  # openhim-mongo-db:
  #   container_name: openhim-mongo-db
  #   image: mongo:4.0
  #   networks:
  #     - openhim
  #   volumes:
  #     - "./mongo-data:/data/db"
  #   restart: unless-stopped

  # openhim-core:
  #   container_name: openhim-core
  #   image: jembi/openhim-core:v7.1.0
  #   restart: unless-stopped
  #   environment:
  #     mongo_url: "mongodb://openhim-mongo-db/openhim-development"
  #     mongo_atnaUrl: "mongodb://openhim-mongo-db/openhim-development"
  #     NODE_ENV: "development"
  #   ports:
  #     - "8083:8080"
  #     - "8084:5000"
  #     - "8085:5001"
  #   networks:
  #     - openhim
  #   healthcheck:
  #     test: "curl -sSk https://openhim-core:8083/heartbeat || exit 1"
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  # openhim-console:
  #   container_name: openhim-console
  #   image: jembi/openhim-console:v1.15.0
  #   restart: unless-stopped
  #   networks:
  #     - openhim
  #   ports:
  #     - "8086:80"
  #   healthcheck:
  #     test: "curl -sS http://openhim-console || exit 1"
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  ddcc:
    container_name: ddcc-transactions-mediator
    image: censcl/ops-ddcc-transactions-mediator:latest
    environment:
      FHIR_SERVER: 'http://hapi-fhir:8080/fhir/'
      MATCHBOX_SERVER: 'http://resource-generation-service:8080/fhir/'
      PRIVATE_KEY_FILE: '/app/cert-data/priv.pem'
    volumes:
      - ./cert-data:/app/cert-data
    ports:
      - "4321:4321"
    depends_on:
      - resource-generation-service

  resource-generation-service:
    container_name: resource-generation-service
    image: censcl/ops-ddcc-resource-generation-service:v1.0
    ports:
        - "8023:8080"

  ips-app:
    container_name: ips-app
    image: createchile/ipsapp_app:latest
    depends_on:
      database-app:
        condition: service_healthy
    ports:
      - "8085:5002"

  database-app:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ips"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init-db-app:/docker-entrypoint-initdb.d/
      - ./postgres-data-app:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminips
      - POSTGRES_DB=ips

  ####### LACCHAIN COMPONENT #########
  lacchain-postgres:
    image: postgres:latest
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: lacchain_postgres_password
      POSTGRES_DB: lacpass_lacchain_db
    volumes:
      - ./lacchain-postgres-data:/var/lib/postgresql/data
    networks:
      - lacchain_backend
  lacchain-redis:
    image: redis:latest
    command: redis-server --requirepass lacchain_redis_password
    ports:
      - "6390:6379"
    networks:
      - lacchain_backend
  lacpass-lacchain:
    image: eumb602/lacpass-client:latest
    environment:
      ENV: prod
      DOCS_ENABLED: "true"
      PORT: 80
      JWT_SECRET: some-secret-string
      TYPEORM_TYPE: postgres
      TYPEORM_HOST: lacchain-postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: lacchain_postgres_password
      TYPEORM_DATABASE: lacpass_lacchain_db
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_MIGRATIONS_RUN: "true"
      REDIS_HOST: lacchain-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: lacchain_redis_password
      ACCESS_TOKEN_LIFE: 360000000
      RATE_LIMIT_WINDOW: 5
      RATE_LIMIT_MAX_REQUESTS: 100
      EMAIL_TRANSPORTER: AWS
      ####### BEGIN OPEN protestnet Configuration #######
      CHAIN_ID: "0x9e55c"
      SECURE_RELAY_MESSAGE_DELIVERER_BASE_URL: https://mailbox.openprotest.lacnet.com
      SECURE_RELAY_MESSAGE_DELIVERER_SEND: /vc
      SECURE_RELAY_SERVICE_DID: did:lac:openprotest:0xf33bc23691245c2d5de99d7d45e9fdd113495870
      DID_RESOLVER_URL: "https://resolver.lacchain.net/"
      NODE_RPC_URL: https://lacpass-openprotest-node.lacchain.net # https://writer-openprotest.lacnet.com
      NODE_ADDRESS: "0x3a8c3cd49347530d1c946cbad5114418e1546dbc" #"0xad730de8c4bfc3d845f7ce851bcf2ea17c049585"
      PUBLIC_DIRECTORY_CONTRACT_ADDRESS: "0xbBbfDe862725186E3D5332618a5546e60fcB75e6"
      CHAIN_OF_TRUST_CONTRACT_ADDRESS: "0xFE7CEF0D8E9A1dab4C4F57154e0191d67D4803AF"
      PROOF_OF_EXISTENCE_MODE: "ENABLED_NOT_THROWABLE" # options: "STRICT", "DISABLED", by default "ENABLED_NOT_THROWABLE"
      VERIFICATION_REGISTRY_CONTRACT_ADDRESS: "0xF17Da8641771c0196318515b662b0C00132C4163"
      ####### END OPEN protestnet Configuration #######
    ports:
      - "3010:80"
    restart: on-failure
    container_name: lacpass-lacchain
    depends_on:
      - lacchain-postgres
      - lacchain-redis
    links:
      - lacchain-postgres
      - lacchain-redis
    networks:
      - lacchain_backend

networks:
  elastic:
  lacchain_backend:
    name: lacchain_backend
