version: '3.8'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - repositories.url.allowed_urls=["https://storage.googleapis.com/snowstorm-preload/"]
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - snowstorm_preload:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 4g


  snowstorm:
    image: kaikewley/snowstorm:10.4.0-beta
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://es:9200
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8180:8080


  snowstorm-browser:
    image: snomedinternational/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
    networks:
      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 8082:80
    restart: always

  init-script-snowstorm:
    image: appropriate/curl
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - .snowstorm-init-status:/status
      - ./init_snowstorm.sh:/usr/local/bin/init_snowstorm.sh
    entrypoint: /bin/sh -c 'sh /usr/local/bin/init_snowstorm.sh'
    networks:
      - elastic
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8089:8080"
    volumes:
      - ./fhir-terminology/connectathon-swagger.yaml:/usr/share/nginx/html/connectathon-swagger.yaml:ro
    environment:
      - SWAGGER_JSON=/connectathon-swagger.yaml
      - VALIDATOR_URL=null
    networks:
      - elastic

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - snowstorm-browser
      - swagger-ui
      - snowstorm
    networks:
      elastic:
        aliases:
         - nginx

networks:
  elastic:

volumes:
  snowstorm_preload:
  db-data:

